from pathlib import Path
import json,hashlib
D=Path(__file__).resolve().parent;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
S=lambda s:r'\mathbf{S}'+s+'{}';E=lambda s:r'\mathbf{E}'+s+'{}';C=lambda s:r'\mathbf{C}'+s+'{}'
figs=[
('1c.pdf',[1098,1106],'Single panel, original D6 monodromy contour',[
('Center point','0'),('Vertical ray above circle, upward arrow',S(r'_1^\infty')),('Vertical radius above0, upward arrow',S('_1^0')),('Vertical radius below0, downward arrow',S('_2^0')+r'e_0^{-2\sigma_3}'),('Vertical ray below circle, downward arrow',S(r'_2^\infty')+r'e_\infty^{2\sigma_3}'),('Right circular semicircle, upward arrow',C(r'_{0\infty}^{+}')),('Left circular semicircle, downward arrow',C(r'_{0\infty}^{-}'))]),
('rotated.pdf',[1233,1241],'Single panel, rotated D6 monodromy contour',[
('Center point','0'),('Upper-right external diagonal ray, outward arrow',S(r'_1^\infty')),('Upper-left inner diagonal radius, outward arrow',S('_1^0')),('Lower-right inner diagonal radius, outward arrow',S('_2^0')+r'e_0^{-2\sigma_3}'),('Lower-left external diagonal ray, outward arrow',S(r'_2^\infty')+r'e_\infty^{2\sigma_3}'),('Right circular arc, arrow upward',C('_1')),('Top circular arc, arrow left',C('_2')),('Left circular arc, arrow downward',C('_3')),('Bottom circular arc, arrow right',C('_4'))]),
('1d.pdf',[1497,1505],'Single panel, D8 monodromy contour',[
('Center point','0'),('Vertical ray below circle, downward arrow',r'\mathrm{i}'+S(r'_1^\infty')+r'\sigma_2'),('Vertical radius below0, downward arrow',r'-\mathrm{i}'+S('_0^0')+r'\sigma_2'),('Circular contour, right upward and left downward arrows',C(r'_{0\infty}'))]),
('2b2.pdf',[1778,1783],'Figure6 left panel, piecewise-constant matrix L',[
('Inner disk',r'\mathbb{I}'),('Exterior of outer circle, printed upper-right',r'\mathbb{I}'),('Inner annulus left of vertical interface',E('^0')),('Inner annulus right of vertical interface',S('_1^0')+E('^0')),('Outer annulus left of vertical interface',E(r'^\infty')),('Outer annulus right of vertical interface',S(r'_1^\infty')+E(r'^\infty'))]),
('3b2.pdf',[1778,1783],'Figure6 right panel, jump contour for Phi_n',[
('Center point','0'),('Vertical external upper ray, upward arrow',S(r'_1^\infty')),('Vertical inner upper radius, upward arrow',S('_1^0')),('Vertical inner lower radius, downward arrow',S('_2^0')+r'e_0^{-2\sigma_3}'),('Vertical lower segment in inner annulus, downward arrow',r'e_1^{-2\sigma_3}'),('Vertical lower segment in outer annulus, downward arrow',r'e_1^{-2\sigma_3}'),('Vertical external lower ray, downward arrow',S(r'_2^\infty')+r'e_\infty^{2\sigma_3}'),('Inner circle right semicircle, upward arrow',r'('+S('_1^0')+E('^0')+r')^{-1}'),('Inner circle left semicircle, downward arrow',r'('+E('^0')+r')^{-1}'),('Middle circle right semicircle, upward arrow',r'e_2^{\sigma_3}'),('Outer circle right semicircle, downward arrow',r'('+S(r'_1^\infty')+E(r'^\infty')+r')^{-1}'),('Outer circle left semicircle, upward arrow',r'('+E(r'^\infty')+r')^{-1}')]),
('2b2-rotated.pdf',[1787,1793],'Figure7, rotated analogue of Figure6, left panel, matrix L',[
('Inner disk',r'\mathbb{I}'),('Exterior of outer circle, printed upper-right',r'\mathbb{I}'),('Inner annulus left printed region',E('^0')),('Inner annulus right printed region',S('_1^0')+E('^0')),('Outer annulus left printed region',E(r'^\infty')),('Outer annulus right printed region',S(r'_1^\infty')+E(r'^\infty'))]),
('3b2-rotated.pdf',[1787,1793],'Figure7, rotated analogue of Figure6, right panel, jump contour',[
('Center point','0'),('External upper-right ray, outward arrow',S(r'_1^\infty')),('Inner upper-left radius, outward arrow',S('_1^0')),('Inner lower-right radius, outward arrow',S('_2^0')+r'e_0^{-2\sigma_3}'),('Thick lower-right segment in inner annulus, outward arrow',r'e_1^{-2\sigma_3}'),('Thick lower-left segment in outer annulus, outward arrow',r'e_1^{-2\sigma_3}'),('Thick external lower-left ray, outward arrow',S(r'_2^\infty')+r'e_\infty^{2\sigma_3}'),('Inner circle upper/right arc, counterclockwise arrow',r'('+S('_1^0')+E('^0')+r')^{-1}'),('Inner circle lower/left arc, downward arrow on left',r'('+E('^0')+r')^{-1}'),('Middle circle thin upper/right arc, upward arrow on right',r'e_2^{\sigma_3}'),('Middle circle thick lower/left arc, arrow right at bottom',r'e_1^{2\sigma_3}e_2^{\sigma_3}'),('Outer circle lower/right arc, downward arrow on right',r'('+S(r'_1^\infty')+E(r'^\infty')+r')^{-1}'),('Outer circle upper/left arc, upward arrow on left',r'('+E(r'^\infty')+r')^{-1}')]),
('4b2.pdf',[1796,1800],'Single panel, infinity parametrix contour',[
('Center point','0'),('External vertical upper ray, upward arrow',S(r'_1^\infty')),('Inner vertical lower radius, downward arrow',r'e_1^{-2\sigma_3}'),('External vertical lower ray, downward arrow',S(r'_2^\infty')+r'e_\infty^{2\sigma_3}'),('Right semicircle, downward arrow',r'('+S(r'_1^\infty')+E(r'^\infty')+r')^{-1}'),('Left semicircle, upward arrow',r'('+E(r'^\infty')+r')^{-1}')]),
('5b2.pdf',[2316,2324],'Single panel, zero parametrix contour',[
('Center point','0'),('Inner vertical upper radius, upward arrow',S('_1^0')),('Inner vertical lower radius, downward arrow',S('_2^0')+r'e_0^{-2\sigma_3}'),('External vertical lower ray, downward arrow',r'e_1^{-2\sigma_3}'),('Right semicircle, upward arrow',r'('+S('_1^0')+E('_0')+r')^{-1}'),('Left semicircle, downward arrow',E('_0')+r'^{-1}')]),
('6.pdf',[3119,3124],'Single panel, S-tilde jump contour',[
('Center point','0'),('External vertical upper ray, upward arrow',S(r'_1^\infty')),('Inner vertical upper radius, upward arrow',S('_0^0')),('Inner vertical lower radius, downward arrow',r'('+S(r'_1^\infty')+r')^{-1}'),('External vertical lower ray, downward arrow',r'('+S('_0^0')+r')^{-1}'),('Right semicircle, upward arrow',C(r'_{0\infty}')),('Left semicircle, downward arrow',r'-\sigma_2'+C(r'_{0\infty}')+r'\sigma_2')]),
('7.pdf',[3211,3216],'Single panel, S-hat jump contour',[
('Center point','0'),('External vertical upper ray, upward arrow',r'\widehat{\mathbf{S}}_1^\infty'),('Inner vertical upper radius, upward arrow',r'\widehat{\mathbf{S}}_0^0'),('Inner vertical lower radius, downward arrow',r'\widehat{\mathbf{S}}_1^\infty'),('External vertical lower ray, downward arrow',r'\widehat{\mathbf{S}}_0^0'),('Right semicircle, upward arrow',r'\widehat{\mathbf{C}}_{0\infty}'),('Left semicircle, downward arrow',r'\sigma_1\widehat{\mathbf{C}}_{0\infty}\sigma_1')])]
text=r'''\clearpage
\section*{Editable transcription of original figure labels}
\noindent\textbf{Source-figure transcription, separate from native author TeX.} The following is a faithful transcription of printed labels in the unchanged original panels. Panel names and geometric/arrow locators are editorial locating aids only; the displayed matrix labels are author figure text, not new equations or derived entries. Figures retain their original curves and arrows. Signs, hats, inverses, printed cases and indices have not been inferred or repaired. In particular the zero-parametrix panel \texttt{5b2.pdf} prints subscript $\mathbf{E}_0$, whereas some other panels print superscript $\mathbf{E}^{0}$; this literal distinction is preserved. Source asset hashes and exact locators are in \texttt{figure-label-transcription-map.json}.
'''
records=[]
for name,lines,title,labels in figs:
 asset=D/'assets-original/Figures'/name;assert asset.exists()
 text+='\n'+r'\subsection*{'+title.replace('_',r'\_')+'}\n'+r'\noindent Original panel: \texttt{Figures/'+name+r'}, native source lines '+str(lines[0])+'--'+str(lines[1])+'.\n'+r'\begin{itemize}\itemsep=0pt'+'\n'
 for loc,math in labels:text+=r'\item '+loc+': $'+math+'$.\n'
 text+=r'\end{itemize}'+'\n';records.append({'asset':'Figures/'+name,'asset_sha256':sha(asset),'native_figure_call_source_lines':lines,'panel':title,'labels':[{'locator':loc,'literal_math_tex':math}for loc,math in labels],'qa_image':'assets-original/Figures/'+name[:-4]+'.png','qa_image_sha256':sha(asset.with_suffix('.png'))})
(D/'figure-labels-transcribed.tex').write_text(text)
(D/'figure-label-transcription-map.json').write_text(json.dumps({'id':'902','role':'Author source-figure labels faithfully transcribed; editorial geometric locators separate; no new proof or derived matrix entries.','source_archive':'corpus/raw/sigma/open-papers-007-2024/0e1bea35be67/source.zip','native_source':'corpus/raw/sigma/open-papers-007-2024/0e1bea35be67/source.tex','transcription_tex_sha256':sha(D/'figure-labels-transcribed.tex'),'verification':'Every matrix/region/jump label checked against rendered original asset pixels; original panels retained unchanged.','panels':records},ensure_ascii=False,indent=2)+'\n')
p=D/'902.tex';t=p.read_text();assert text not in t;t=t.replace(r'\begin{thebibliography}{99}',text+'\n'+r'\begin{thebibliography}{99}');p.write_text(t)
print('transcribed',sum(len(x[3])for x in figs),'literal labels across',len(figs),'original panels')
